name: AutoLogin Builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller win10toast requests
    - name: Build
      run: |
        pyinstaller -F -w AutoLogin.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: /dist/AutoLogin.exe # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /dist/AutoLogin.exe
        # The desired behavior if no files are found using the provided path.
